CREATE DATABASE dogGo;

USE dogGo;

CREATE TABLE walkers (
id INTEGER NOT NULL AUTO_INCREMENT,
first_name VARCHAR (50) NOT NULL,
last_name VARCHAR (50) NOT NULL,
rating DECIMAL (2,1),
PRIMARY KEY (id)
);

CREATE TABLE customers (
id INTEGER NOT NULL AUTO_INCREMENT,
name VARCHAR (50),
petName VARCHAR (50),
email VARCHAR (128) NOT NULL,
phone VARCHAR (10) NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE service (
id INTEGER NOT NULL AUTO_INCREMENT,
serviceName VARCHAR (50),
duration INTEGER,
price DECIMAL (10,2),
PRIMARY KEY (id)
);





SELECT * FROM walkers;
SELECT * FROM customers;
SELECT * FROM service;