DROP DATABASE IF EXISTS dogGo;
CREATE DATABASE dogGo;

USE dogGo;

CREATE TABLE walkers (
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR (100) NOT NULL,
email VARCHAR (50) NOT NULL,
phoneNumber VARCHAR(12) NOT NULL
);

CREATE TABLE customers (
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR (50),
petName VARCHAR (50),
email VARCHAR (128) NOT NULL UNIQUE,
phoneNumber VARCHAR(12) NOT NULL
);

CREATE TABLE appointments (
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
date DATE NOT NULL,
startTime TIME NOT NULL,
walkerChosen INT REFERENCES walkers(ID),
customerID INT REFERENCES customers(ID),
overnightChosen BOOL DEFAULT false,
available BOOL DEFAULT true

);




SELECT * FROM walkers;
SELECT * FROM customers;
SELECT * FROM service;